apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-processor
  namespace: csv-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-processor
  template:
    metadata:
      labels:
        app: csv-processor
    spec:
      containers:
      - name: csv-processor
        image: csv-processor:latest
        imagePullPolicy: Never
        env:
        - name: MONGODB_URI
          value: mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongodb-service:27017
        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      - name: data-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: csv-processor-service
  namespace: csv-processor
spec:
  selector:
    app: csv-processor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000