apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: users-api
  labels:
    app: users-api
spec:
  type: NodePort
  selector:
    app: users-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080