apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: users-api
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=     # postgres en base64
  POSTGRES_PASSWORD: MTIzNGFiY2Q=  # 1234abcd en base64
  POSTGRES_DB: c2FsZXNfZGI=       # sales_db en base64